version: '3'

tasks:
  start:
    env:
      DATABASE_URL: postgres://postgres:060216@localhost:5432/cowlist
      POSTGRES_PASSWORD: 060216
    cmds:
      - docker compose up -d
      - go run cmd/main.go
